# Generated by Django 5.2 on 2025-04-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_notifications_enabled_and_more'),
    ]

    operations = [
    ]
