services:
  - type: web
    name: wellness-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn wellness_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wellness-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SPOONACULAR_API_KEY
        sync: false
  - type: web
    name: wellness-frontend
    env: static
    buildCommand: |
      cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist

databases:
  - name: wellness-db
    plan: free
