# Generated by Django 5.2 on 2025-05-14 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('weight', 'Weight Goal'), ('activity', 'Activity Level'), ('habit', 'Habit Streak')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('progress_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('progress_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achieved_at'],
            },
        ),
    ]
