# Generated by Django 4.2.22 on 2025-07-13 20:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0003_add_healt_summary'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='healthsummary',
            name='unique_user_summary_period',
        ),
        migrations.RemoveConstraint(
            model_name='summarymetric',
            name='unique_summary_metric',
        ),
        migrations.AlterUniqueTogether(
            name='healthsummary',
            unique_together={('user', 'summary_type', 'start_date', 'end_date')},
        ),
        migrations.AlterUniqueTogether(
            name='summarymetric',
            unique_together={('summary', 'metric_name')},
        ),
    ]
