# Generated by Django 5.2 on 2025-04-13 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='avg_session_duration',
            field=models.CharField(blank=True, choices=[('short', '15-30 minutes'), ('medium', '30-60 minutes'), ('long', '60+ minutes')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='dietary_preference',
            field=models.CharField(blank=True, choices=[('omnivore', 'Omnivore (Eats Everything)'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('pescatarian', 'Pescatarian'), ('keto', 'Keto'), ('paleo', 'Paleo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='does_cardio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='does_flexibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='does_sports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='does_strength',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='endurance_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum minutes can run/walk continuously', null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='fitness_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='has_other_restrictions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='is_dairy_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='is_gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='is_nut_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='other_restrictions_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='preferred_environment',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('gym', 'Gym'), ('outdoors', 'Outdoors')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='pushup_count',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of pushups in one set', null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='squat_count',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of bodyweight squats in one set', null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='time_preference',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='weekly_activity_days',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(7)]),
        ),
    ]
