# Generated by Django 5.2 on 2025-05-20 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_profiles', '0002_healthprofile_avg_session_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('activity_type', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength Training'), ('flexibility', 'Flexibility/Stretching'), ('sports', 'Sports'), ('hiit', 'HIIT'), ('yoga', 'Yoga'), ('other', 'Other')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('location', models.CharField(choices=[('home', 'Home'), ('gym', 'Gym'), ('outdoors', 'Outdoors'), ('other', 'Other')], default='home', max_length=20)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='weighthistory',
            constraint=models.UniqueConstraint(fields=('health_profile', 'recorded_at'), name='unique_weight_entry_timestamp'),
        ),
        migrations.AddField(
            model_name='activity',
            name='health_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='health_profiles.healthprofile'),
        ),
    ]
